### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by peterdfields** [machinegun/hi-c-scaffold#1]
I tried compiling the code provided on a CentOS 7 machine. Initial run of make results in the following:

`Makefile:2: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.`

replacement of the spaces with a tab in the Makefile results in the following error:

`g++ break_contigs.cpp -std=c++11 -o break_contigs
break_contigs.cpp:12:21: fatal error: cmdline.h: No such file or directory
 #include "cmdline.h"
                     ^
compilation terminated.
make: *** [all] Error 1`

**Comment by machinegun** [comment]
Fixed the error.
