### ISSUE TITLE
bam2Bed & contig lengths

### ISSUE THREAD

**Issue by fbemm** [machinegun/hi-c-scaffold#2]
I just started to play around with the tool. Couple of things popped up.

1. Where to report issues and commit/send pull requests to machinegun/hi-c-scaffold or pb-jchin/hi-c-scaffold?

2. Biopython is missing in the requirements section.

3. I had to manually index the contigs (samtools faidx and extract the contig lenghts)  and call bam2Bed since the code block doing it is commented out.

I have plenty of data sets for different species (some Dovetail'd) and happy to benchmark your tool :+1:

**Comment by pb-jchin** [comment]
I am chatting with @machinegun to see how we are going to organize this.  Currently, please send PR to @machinegun's repository for now.  BTW, the code is relative simple, and we mostly test on a set of human data. We will be interested in see how the idea / the code works with other data too.
