### ISSUE TITLE
Error in links_to_graph3.py", line 413

### ISSUE THREAD

**Issue by fbemm** [machinegun/hi-c-scaffold#3]
Got the first error ;)

Seems related to lower and upper case bases int the contig file. Test with upper-cases only is running.

started scaffolding
Traceback (most recent call last):
  File "links_to_graph3.py", line 413, in <module>
    main()
  File "links_to_graph3.py", line 402, in main
    curr_contig += revcompl(id2seq[curr[0]])
  File "links_to_graph3.py", line 7, in <lambda>
    revcompl = lambda x: ''.join([{'A':'T','C':'G','G':'C','T':'A'}[B] for B in x][::-1])
KeyError: 'a'
done scaffolding, sequences written to file

**Comment by machinegun** [comment]
Thanks for pointing that out. Fixed this error now.

**Comment by fbemm** [comment]
Upper case contigs work. Scaffolded 123 contigs (N50 10Mb) into 4 scaffolds (N50 29Mb). Expectation for this one is five so a good test and debug case. I guess a bit of repeat masking or thining of the alignments will do the job. Very promising ;)

**Comment by machinegun** [comment]
There should be a file in the output directory named 'paths' where there will be contig-paths those gave scaffolds in following format:

```
scaffold_number
contig1
contig2
.
.
```
However, this is not a good format to output. I will think of some better way. Currently there is not output file stating unplaced contigs. I will add that feature.

**Comment by fbemm** [comment]
Thx!
