### ISSUE TITLE
Genome sequence always have lowercase ’n‘ error

### ISSUE THREAD

**Issue by liufuyan2016** [machinegun/hi-c-scaffold#7]
The Genome sequence always have lowercase ’n‘， however the code did not have:
**revcompl = lambda x: ''.join([{'A':'T','C':'G','G':'C','T':'A','N':'N','R':'N','M':'N','Y':'N','S':'N','W':'N','K':'N','a':'t','c':'g','g':'c','t':'a',' ':'',}[B] for B in x][::-1])**
This is a bug. Hope the author fixed!

**Comment by machinegun** [comment]
fixed. Thanks
